variables:
    IMAGE_TAG_WEB: $CI_REGISTRY_IMAGE:web
    IMAGE_TAG_WORKER: $CI_REGISTRY_IMAGE:worker

stages:
    - lint
    - build

lint:
    image: node:8-alpine
    stage: lint
    cache:
        paths:
            - node_modules/
    script:
        - yarn
        - yarn run lint

build-web:
    image: docker:latest
    stage: build
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $IMAGE_TAG_WEB -f Dockerfile.web .
        - docker push $IMAGE_TAG_WEB

build-worker:
    image: docker:latest
    stage: build
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $IMAGE_TAG_WORKER -f Dockerfile.worker .
        - docker push $IMAGE_TAG_WORKER
