stages:
    - lint
    - build

lint:
    image: node:8-alpine
    stage: lint
    cache:
        paths:
            - node_modules/
    script:
        - yarn
        - yarn run lint

build-api:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t api:${CI_COMMIT_SHA:0:8} -f Dockerfile.api .
        - docker push api:${CI_COMMIT_SHA:0:8}

build-worker:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    variables:
        IMAGE_TAG: worker:${CI_COMMIT_SHA:0:8}
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t worker:${CI_COMMIT_SHA:0:8} -f Dockerfile.worker .
        - docker push worker:${CI_COMMIT_SHA:0:8}

build-scheduler:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t scheduler:${CI_COMMIT_SHA:0:8} -f Dockerfile.scheduler .
        - docker push scheduler:${CI_COMMIT_SHA:0:8}
