variables:
    IMAGE_TAG_API: $CI_REGISTRY_IMAGE/api:${CI_COMMIT_SHA:0:8}
    IMAGE_TAG_WORKER: $CI_REGISTRY_IMAGE/worker:${CI_COMMIT_SHA:0:8}
    IMAGE_TAG_SCHEDULER: $CI_REGISTRY_IMAGE/scheduler:${CI_COMMIT_SHA:0:8}

stages:
    - lint
    - build

lint:
    image: node:8-alpine
    stage: lint
    cache:
        paths:
            - node_modules/
    script:
        - yarn
        - yarn run lint

build-api:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $IMAGE_TAG_API -f Dockerfile.api .
        - docker push $IMAGE_TAG_API

build-worker:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    variables:
        IMAGE_TAG: worker:${CI_COMMIT_SHA:0:8}
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $IMAGE_TAG_WORKER -f Dockerfile.worker .
        - docker push $IMAGE_TAG_WORKER

build-scheduler:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $IMAGE_TAG_SCHEDULER -f Dockerfile.scheduler .
        - docker push $IMAGE_TAG_SCHEDULER
