cache:
    paths:
        - node_modules/

variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

before_script:
    - yarn

stages:
    - lint
    - build
    - deploy

lint:
    image: node:8-alpine
    stage: lint
    script:
        - yarn run lint

build:
    image: docker:latest
    stage: build
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $IMAGE_TAG .
        - docker push $IMAGE_TAG

deploy:
    image: alpine:latest
    stage: deploy
    only:
        - master
    script:
        - apk add --update git openssh-client
        - mkdir -p ~/.ssh
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - ssh-keyscan -p 2222 -H 'warcraftjournal.org' >> ~/.ssh/known_hosts
        - echo -e 'Host warcraftjournal.org\n    Port 2222' >> ~/.ssh/config
        - git push dokku@warcraftjournal.org:warcraftjournal-api-staging master
    environment:
        name: staging
        url: https://api.staging.warcraftjournal.org
