stages:
    - lint
    - build

lint:
    image: node:8-alpine
    stage: lint
    cache:
        paths:
            - node_modules/
    script:
        - yarn
        - yarn run lint

build-api:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    variables:
        IMAGE_TAG: api:${CI_COMMIT_SHA:0:8}
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t ${IMAGE_TAG} -f Dockerfile.api .
        - docker push $IMAGE_TAG

build-worker:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    variables:
        IMAGE_TAG: worker:${CI_COMMIT_SHA:0:8}
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t ${IMAGE_TAG} -f Dockerfile.worker .
        - docker push $IMAGE_TAG

build-worker:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    variables:
        IMAGE_TAG: scheduler:${CI_COMMIT_SHA:0:8}
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t ${IMAGE_TAG} -f Dockerfile.scheduler .
        - docker push $IMAGE_TAG
