variables:
    IMAGE_TAG_API: $CI_REGISTRY_IMAGE/api
    IMAGE_TAG_WORKER: $CI_REGISTRY_IMAGE/worker
    IMAGE_TAG_SCHEDULER: $CI_REGISTRY_IMAGE/scheduler

stages:
    - lint
    - build

lint:
    image: node:8-alpine
    stage: lint
    cache:
        paths:
            - node_modules/
    script:
        - yarn
        - yarn run lint

build-api:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $IMAGE_TAG_API:${CI_COMMIT_SHA:0:8} --build-arg COMPONENT_NAME=api -f Dockerfile.api .
        - docker push $IMAGE_TAG_API:${CI_COMMIT_SHA:0:8}

build-worker:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    variables:
        IMAGE_TAG: worker:${CI_COMMIT_SHA:0:8}
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $IMAGE_TAG_WORKER:${CI_COMMIT_SHA:0:8} --build-arg COMPONENT_NAME=worker -f Dockerfile.worker .
        - docker push $IMAGE_TAG_WORKER:${CI_COMMIT_SHA:0:8}

build-scheduler:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $IMAGE_TAG_SCHEDULER:${CI_COMMIT_SHA:0:8} --build-arg COMPONENT_NAME=scheduler -f Dockerfile.scheduler .
        - docker push $IMAGE_TAG_SCHEDULER:${CI_COMMIT_SHA:0:8}
